//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appraisal
    {
        public int AppraisalId { get; set; }
        public System.DateTime DateInitiated { get; set; }
        public int AppraisalYearId { get; set; }
        public int AppraisalPeriodId { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsOpened { get; set; }
    }
}
