//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalQuantitiveMetric
    {
        public int AppraisalQuantitativeMetricId { get; set; }
        public int EmployeeAppraisalId { get; set; }
        public string PrimaryTarget { get; set; }
        public string PrimaryActual { get; set; }
        public string SecondaryTarget { get; set; }
        public string SecondaryActual { get; set; }
        public Nullable<int> ResultId { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
