//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefit
    {
        public int BenefitId { get; set; }
        public string BenefitName { get; set; }
        public string BenefitDescription { get; set; }
        public bool IsMonetized { get; set; }
        public bool IsTaxable { get; set; }
        public int Period { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsActive { get; set; }
    }
}
