//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangePassword
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
