//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public string CACRegistrationNumber { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAlias { get; set; }
        public string CompanyAddressLine1 { get; set; }
        public string CompanyAddressLine2 { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyState { get; set; }
        public int CompanyCountryId { get; set; }
        public Nullable<int> CompanyZipCode { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyWebsite { get; set; }
        public Nullable<int> LogoDigitalFileId { get; set; }
        public Nullable<int> ParentCompanyId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public int IndustryId { get; set; }
    }
}
