//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public int DeductionId { get; set; }
        public string DeductionName { get; set; }
        public decimal DeductionAmount { get; set; }
        public int CompanyId { get; set; }
        public int EmployeeId { get; set; }
        public bool IsTerminated { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateStarted { get; set; }
        public Nullable<System.DateTime> DateTerminated { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
