//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalFile
    {
        public int DigitalFileId { get; set; }
        public byte[] TheDigitalFile { get; set; }
        public int DigitalTypeId { get; set; }
        public string FileExtension { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public string ContentType { get; set; }
        public string FileName { get; set; }
    }
}
