//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationHistory
    {
        public int EducationHistoryId { get; set; }
        public int EmployeeId { get; set; }
        public string SchoolName { get; set; }
        public string Degree { get; set; }
        public int GraduationYear { get; set; }
        public string Note { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
    }
}
