//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAnnualAssessingPerformance
    {
        public int EmployeeAnnualAssesssingPerformanceId { get; set; }
        public int AnnualAssessingPerformanceId { get; set; }
        public string Thing_I_Did_Well { get; set; }
        public string Things_I_Did_Not_Do_Well { get; set; }
        public string Driven_Exceptional_Client_Service { get; set; }
        public string Highest_Performing_Teams { get; set; }
        public string Examples_Of_Living_Our_Values { get; set; }
        public string Enhanced_Quality_And_Effective_Risk_Management { get; set; }
        public Nullable<int> ReviewerRatingId { get; set; }
        public Nullable<int> RevieweeRatingId { get; set; }
        public Nullable<int> FinalRatingId { get; set; }
        public string ReviewerComment { get; set; }
        public string FinalRatingComment { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> RevieweeId { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public Nullable<int> FinalReviewerId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateOfReviewee { get; set; }
        public Nullable<System.DateTime> DateOfReviewer { get; set; }
        public Nullable<System.DateTime> DateOfFinalReview { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
    }
}
