//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFeedback
    {
        public int EmployeeFeedbackId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> FeedbackOnEmployeeId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateOfFeedback { get; set; }
        public int FeedbackId { get; set; }
        public bool IsActive { get; set; }
        public string InWhatContext { get; set; }
        public string ProvideOverview { get; set; }
        public string Experience { get; set; }
        public string WhatAreas { get; set; }
    }
}
