//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAppraisal
    {
        public int EmployeeAppraisalId { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public int AppraisalId { get; set; }
        public int EmployeeId { get; set; }
        public string Things_I_Did_Well { get; set; }
        public string Things_I_Did_Not_Do_So_Well { get; set; }
        public string My_Development_Plan { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsActive { get; set; }
        public int CompanyId { get; set; }
    }
}
