//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExit
    {
        public int EmployeeExitId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime DateRequested { get; set; }
        public string Reason { get; set; }
        public int TypeOfExitId { get; set; }
        public string ExitInterViewSummary { get; set; }
        public string Interviewer { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
    }
}
