//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeQuestionRating
    {
        public int EmployeeQuestionRatingId { get; set; }
        public int EmployeeId { get; set; }
        public int AppraisalQuestionId { get; set; }
        public int EmployeeAppraisalId { get; set; }
        public int AppraisalId { get; set; }
        public int AppraiseeRatingId { get; set; }
        public int AppraiserRatingId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
