//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string StaffNumber { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public int CompanyId { get; set; }
        public int LevelId { get; set; }
        public int GradeId { get; set; }
        public int EmploymentTypeId { get; set; }
        public string MobileNumber { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentAddressCity { get; set; }
        public int PermanentAddressState { get; set; }
        public string HomeAddress { get; set; }
        public string HomeAddressCity { get; set; }
        public int HomeAddressState { get; set; }
        public string OtherEmail { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string GenderOther { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime DateEmployed { get; set; }
        public string About { get; set; }
        public Nullable<System.DateTime> DateExited { get; set; }
        public string SkillSet { get; set; }
        public Nullable<int> SupervisorEmployeeId { get; set; }
        public string SeatingLocation { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string MaidenName { get; set; }
        public Nullable<int> PhotoDigitalFileId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public string ReligionOther { get; set; }
        public int Nationality { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsExit { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
    }
}
