//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTraining
    {
        public int EmployeeTrainingId { get; set; }
        public int TrainingId { get; set; }
        public int TrainingReportId { get; set; }
        public int EmployeeId { get; set; }
        public int SupervisorId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CompanyId { get; set; }
    }
}
