//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplicationVacancyAnswer
    {
        public int JobApplicationVacancyAnswerId { get; set; }
        public int VacancyQuestionId { get; set; }
        public int JobApplicationVacancyId { get; set; }
        public string Answer { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
