//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        public int LeaveID { get; set; }
        public int EmployeeID { get; set; }
        public int CompanyID { get; set; }
        public bool IsActive { get; set; }
        public int LeaveTypeID { get; set; }
        public System.DateTime DateLeaveStart { get; set; }
        public System.DateTime DateLeaveEnds { get; set; }
        public string Comment { get; set; }
        public int LeaveStatusID { get; set; }
        public System.DateTime DateRequested { get; set; }
        public Nullable<int> ApprovingAuthorityID { get; set; }
        public Nullable<int> HRApproverID { get; set; }
        public string ApprovingAuthorityComment { get; set; }
        public string HRApproverComment { get; set; }
        public Nullable<System.DateTime> DateApprovedDept { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateApprovedHR { get; set; }
    }
}
