//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milestone
    {
        public int MilestoneId { get; set; }
        public string MilestoneName { get; set; }
        public string MilestoneDescription { get; set; }
        public Nullable<bool> hasStarted { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<bool> hasCompleted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string ApprovalComment { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public int TaskId { get; set; }
    }
}
