//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverTimesheet
    {
        public int OverTimesheetId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime OverTimeDate { get; set; }
        public int NumberofHours { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CompanyId { get; set; }
    }
}
