//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollHistory
    {
        public int PayrollHistoryId { get; set; }
        public int Year { get; set; }
        public string MonthCode { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
    }
}
