//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileId { get; set; }
        public int UserId { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string StateOfOrigin { get; set; }
        public int GenderId { get; set; }
        public string GenderOther { get; set; }
        public int CountryId { get; set; }
        public string ProfileSummary { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int PictureDigitalFileId { get; set; }
        public int CVDigitalFileId { get; set; }
    }
}
