//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int PromotionId { get; set; }
        public int EmployeeId { get; set; }
        public int LevelId { get; set; }
        public int GradeId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DatePromoted { get; set; }
        public bool IsActive { get; set; }
    }
}
