//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public string ScheduleName { get; set; }
        public int WeekId { get; set; }
        public int DayId { get; set; }
        public bool IsActive { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
