//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingNeedAnalysi
    {
        public int TrainingNeedAnaylsisId { get; set; }
        public int JobId { get; set; }
        public int CompanyId { get; set; }
        public int TrainingId { get; set; }
        public string TrainingDescription { get; set; }
        public int MethodOfDelivery { get; set; }
        public string TrainingProvider { get; set; }
        public decimal Cost { get; set; }
        public int CurrencyId { get; set; }
        public string Location { get; set; }
        public bool IsProviderApproved { get; set; }
        public decimal ApprovedBudget { get; set; }
        public int ApprovedBudgetCurrency { get; set; }
        public int FrequecyOfDeliveryId { get; set; }
        public decimal TrainingDuration { get; set; }
        public string CertificateIssued { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
    }
}
