//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCalender
    {
        public int TrainingCalenderId { get; set; }
        public int TrainingId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime DeliveryStartDate { get; set; }
        public System.DateTime DeliveryEndDate { get; set; }
        public string Location { get; set; }
        public int TrainingStatusId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
    }
}
