//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingReport
    {
        public int TrainingReportId { get; set; }
        public int TrainingId { get; set; }
        public int CompanyId { get; set; }
        public int EmployeeId { get; set; }
        public int TrainingCalendarId { get; set; }
        public string TrainerName { get; set; }
        public string TrainerEvaluationComment { get; set; }
        public int TrainerEvaluationRating { get; set; }
        public string TrainingEvaluationComment { get; set; }
        public int TrainingEvaluationRating { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
