//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAppRole
    {
        public string Username { get; set; }
        public int AppRoleId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreateByUsername { get; set; }
        public int UserAppRoleId { get; set; }
    }
}
