//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsUserVerified { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsResetPassword { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
    }
}
