//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacancyQuestion
    {
        public int VacancyQuestionId { get; set; }
        public int VacancyId { get; set; }
        public string Question { get; set; }
        public int AnswerFormatId { get; set; }
        public bool IsAnswerRequired { get; set; }
        public bool IsActive { get; set; }
    }
}
