//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public int VacancyId { get; set; }
        public int CompanyId { get; set; }
        public int DepartmentId { get; set; }
        public int JobTitleId { get; set; }
        public int GradeId { get; set; }
        public string JobTitle { get; set; }
        public string JobFunction { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public int NumberToEmploy { get; set; }
        public System.DateTime OpenDate { get; set; }
        public System.DateTime Closedate { get; set; }
        public bool IsActive { get; set; }
    }
}
