//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AA.HRMS.Domain.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select About Us Source].
        /// </summary>
        public static string SelectAboutUsSourceText {
            get {
                return ResourceManager.GetString("SelectAboutUsSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Appraisal Action].
        /// </summary>
        public static string SelectAppraisalActionText {
            get {
                return ResourceManager.GetString("SelectAppraisalActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Appraisal Rating].
        /// </summary>
        public static string SelectAppraisalRatingText {
            get {
                return ResourceManager.GetString("SelectAppraisalRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Appraisal].
        /// </summary>
        public static string SelectAppraisalText {
            get {
                return ResourceManager.GetString("SelectAppraisalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Appraiser].
        /// </summary>
        public static string SelectAppraiserText {
            get {
                return ResourceManager.GetString("SelectAppraiserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Role].
        /// </summary>
        public static string SelectAppRoleText {
            get {
                return ResourceManager.GetString("SelectAppRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Benefit].
        /// </summary>
        public static string SelectBenefit {
            get {
                return ResourceManager.GetString("SelectBenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Company].
        /// </summary>
        public static string SelectCompanyText {
            get {
                return ResourceManager.GetString("SelectCompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Country].
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Currency].
        /// </summary>
        public static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Deduction].
        /// </summary>
        public static string SelectDeduction {
            get {
                return ResourceManager.GetString("SelectDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Department].
        /// </summary>
        public static string SelectDepartmentText {
            get {
                return ResourceManager.GetString("SelectDepartmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select ActionTaken].
        /// </summary>
        public static string SelectedActionTaken {
            get {
                return ResourceManager.GetString("SelectedActionTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Period].
        /// </summary>
        public static string SelectedAppraisalPeriod {
            get {
                return ResourceManager.GetString("SelectedAppraisalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Method of Delivery].
        /// </summary>
        public static string SelectedMethodOfDelivery {
            get {
                return ResourceManager.GetString("SelectedMethodOfDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Query Status].
        /// </summary>
        public static string SelectedQuery {
            get {
                return ResourceManager.GetString("SelectedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Training Calendar].
        /// </summary>
        public static string selectedTrainingCalendarText {
            get {
                return ResourceManager.GetString("selectedTrainingCalendarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Employee].
        /// </summary>
        public static string SelectEmployeeText {
            get {
                return ResourceManager.GetString("SelectEmployeeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Employment Type].
        /// </summary>
        public static string SelectEmploymentTypeText {
            get {
                return ResourceManager.GetString("SelectEmploymentTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Experience].
        /// </summary>
        public static string SelectExperience {
            get {
                return ResourceManager.GetString("SelectExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Frequency of Delivery].
        /// </summary>
        public static string SelectFrequencyOfDeliveryText {
            get {
                return ResourceManager.GetString("SelectFrequencyOfDeliveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Gender].
        /// </summary>
        public static string SelectGenderText {
            get {
                return ResourceManager.GetString("SelectGenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Grade].
        /// </summary>
        public static string SelectGradeText {
            get {
                return ResourceManager.GetString("SelectGradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Industry].
        /// </summary>
        public static string SelectIndustry {
            get {
                return ResourceManager.GetString("SelectIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select JobTitle].
        /// </summary>
        public static string SelectJobTitleText {
            get {
                return ResourceManager.GetString("SelectJobTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Leave Status Text].
        /// </summary>
        public static string SelectLeaveStatusText {
            get {
                return ResourceManager.GetString("SelectLeaveStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Leave Type].
        /// </summary>
        public static string SelectLeaveTypeText {
            get {
                return ResourceManager.GetString("SelectLeaveTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Level].
        /// </summary>
        public static string SelectLevelText {
            get {
                return ResourceManager.GetString("SelectLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Loan].
        /// </summary>
        public static string SelectLoanText {
            get {
                return ResourceManager.GetString("SelectLoanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select MaritalStatus].
        /// </summary>
        public static string SelectMaritalStatusText {
            get {
                return ResourceManager.GetString("SelectMaritalStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Month].
        /// </summary>
        public static string SelectMonth {
            get {
                return ResourceManager.GetString("SelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Parent Company].
        /// </summary>
        public static string SelectParentCompanyText {
            get {
                return ResourceManager.GetString("SelectParentCompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Grade Level].
        /// </summary>
        public static string SelectPayScale {
            get {
                return ResourceManager.GetString("SelectPayScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Religion].
        /// </summary>
        public static string SelectReligionText {
            get {
                return ResourceManager.GetString("SelectReligionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Reward].
        /// </summary>
        public static string SelectRewards {
            get {
                return ResourceManager.GetString("SelectRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select State].
        /// </summary>
        public static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Tax].
        /// </summary>
        public static string SelectTaxText {
            get {
                return ResourceManager.GetString("SelectTaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Training Rating].
        /// </summary>
        public static string SelectTrainingEvaluationText {
            get {
                return ResourceManager.GetString("SelectTrainingEvaluationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Status].
        /// </summary>
        public static string SelectTrainingStatusText {
            get {
                return ResourceManager.GetString("SelectTrainingStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Training].
        /// </summary>
        public static string SelectTrainingText {
            get {
                return ResourceManager.GetString("SelectTrainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Type Of Exit].
        /// </summary>
        public static string SelectTypeOfExitText {
            get {
                return ResourceManager.GetString("SelectTypeOfExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Year].
        /// </summary>
        public static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
    }
}
