//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA.HRMS.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AA.HRMS.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already applied for this job.
        /// </summary>
        public static string AlreadyApplied {
            get {
                return ResourceManager.GetString("AlreadyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an already running loan.
        /// </summary>
        public static string AlreadyRunningLoan {
            get {
                return ResourceManager.GetString("AlreadyRunningLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Assessing Performance Already Exist.
        /// </summary>
        public static string AnnualAssessingPerformanceAlreadyExist {
            get {
                return ResourceManager.GetString("AnnualAssessingPerformanceAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree already exist.
        /// </summary>
        public static string ApplicationEducationHistoryAlreadyExisted {
            get {
                return ResourceManager.GetString("ApplicationEducationHistoryAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Already Exist for this Year and Period.
        /// </summary>
        public static string AppraisalAlreadyExist {
            get {
                return ResourceManager.GetString("AppraisalAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award already exist.
        /// </summary>
        public static string AwardAlreadyExist {
            get {
                return ResourceManager.GetString("AwardAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Already exist.
        /// </summary>
        public static string BeneficiaryAlreadyExists {
            get {
                return ResourceManager.GetString("BeneficiaryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit Already Exist .
        /// </summary>
        public static string BenefitAlreadyExisted {
            get {
                return ResourceManager.GetString("BenefitAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company CAC number already existed, please check and try again.
        /// </summary>
        public static string CACNumberAlreadyExisted {
            get {
                return ResourceManager.GetString("CACNumberAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHild Information Already Exist.
        /// </summary>
        public static string ChildInformationAlreadyExist {
            get {
                return ResourceManager.GetString("ChildInformationAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information does not exit. Please check.
        /// </summary>
        public static string CompanyInfomationDoesNotExist {
            get {
                return ResourceManager.GetString("CompanyInfomationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company must be a child of an existing Company.
        /// </summary>
        public static string CompanyMostBeAChildofExistingCompany {
            get {
                return ResourceManager.GetString("CompanyMostBeAChildofExistingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Setup Not Complete.
        /// </summary>
        public static string CompanySetupNotComplete {
            get {
                return ResourceManager.GetString("CompanySetupNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email to confirm your registration.
        /// </summary>
        public static string ConfirmRegistrationText {
            get {
                return ResourceManager.GetString("ConfirmRegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is Created.
        /// </summary>
        public static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Already Exist.
        /// </summary>
        public static string DeductionAlreadyExist {
            get {
                return ResourceManager.GetString("DeductionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name already exist.
        /// </summary>
        public static string DepartmentAlreadyExisted {
            get {
                return ResourceManager.GetString("DepartmentAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already used for registration..
        /// </summary>
        public static string EmailAlreadyUsedText {
            get {
                return ResourceManager.GetString("EmailAlreadyUsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Does Not Exist.
        /// </summary>
        public static string EmailDoesNotExist {
            get {
                return ResourceManager.GetString("EmailDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact already exists.
        /// </summary>
        public static string EmergencyContactAlreadyExists {
            get {
                return ResourceManager.GetString("EmergencyContactAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Feedback already Exist.
        /// </summary>
        public static string EmployeeFeedBackAlreadyExist {
            get {
                return ResourceManager.GetString("EmployeeFeedBackAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment History Already Exist.
        /// </summary>
        public static string EmploymentHistoryAlreadyExisted {
            get {
                return ResourceManager.GetString("EmploymentHistoryAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Type Already Exist.
        /// </summary>
        public static string ExitTypeAlreayExist {
            get {
                return ResourceManager.GetString("ExitTypeAlreayExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Already Exist.
        /// </summary>
        public static string FeedBackAlreadyExist {
            get {
                return ResourceManager.GetString("FeedBackAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Name already exist.
        /// </summary>
        public static string GradeAlreadyExisted {
            get {
                return ResourceManager.GetString("GradeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Grade Does Not Exist.
        /// </summary>
        public static string gradeRecordExist {
            get {
                return ResourceManager.GetString("gradeRecordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string IncorrectPasswordText {
            get {
                return ResourceManager.GetString("IncorrectPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry already exist, Please check.
        /// </summary>
        public static string IndustryAlreadyExisted {
            get {
                return ResourceManager.GetString("IndustryAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code is Invalid..
        /// </summary>
        public static string InvalidActivationCode {
            get {
                return ResourceManager.GetString("InvalidActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title Already Exist .
        /// </summary>
        public static string JobTitleAlreadyExist {
            get {
                return ResourceManager.GetString("JobTitleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a pending leave.
        /// </summary>
        public static string LeavePending {
            get {
                return ResourceManager.GetString("LeavePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a running leave.
        /// </summary>
        public static string LeaveRunning {
            get {
                return ResourceManager.GetString("LeaveRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type Already Exist.
        /// </summary>
        public static string LeaveTypeNameAlreadyExist {
            get {
                return ResourceManager.GetString("LeaveTypeNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Level or Grade Record Exit.
        /// </summary>
        public static string levelGradeRecordExist {
            get {
                return ResourceManager.GetString("levelGradeRecordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Name Already Exist.
        /// </summary>
        public static string LevelRecordAlreadyExit {
            get {
                return ResourceManager.GetString("LevelRecordAlreadyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee(s) salary scale not set. Check you employee records..
        /// </summary>
        public static string levelRecordExist {
            get {
                return ResourceManager.GetString("levelRecordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next of Kin already exist.
        /// </summary>
        public static string NextOfKinExistText {
            get {
                return ResourceManager.GetString("NextOfKinExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Employee Record.
        /// </summary>
        public static string NoEmployeeRecord {
            get {
                return ResourceManager.GetString("NoEmployeeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee already exist.
        /// </summary>
        public static string OnBoarderAlreadyExist {
            get {
                return ResourceManager.GetString("OnBoarderAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Department not setup for Company.
        /// </summary>
        public static string ParentDepartmentNotSetupText {
            get {
                return ResourceManager.GetString("ParentDepartmentNotSetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a password..
        /// </summary>
        public static string PasswordValidationError {
            get {
                return ResourceManager.GetString("PasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Already Exist.
        /// </summary>
        public static string PayrollAlreadyExist {
            get {
                return ResourceManager.GetString("PayrollAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Scale Already Exist.
        /// </summary>
        public static string payScaleAlreadyExist {
            get {
                return ResourceManager.GetString("payScaleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or More PayScale not set .
        /// </summary>
        public static string PayScaleNotSet {
            get {
                return ResourceManager.GetString("PayScaleNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is not good enough to apply for a job , Please update add a profile and education history to apply.
        /// </summary>
        public static string ProfileDoesntExist {
            get {
                return ResourceManager.GetString("ProfileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Already Exist.
        /// </summary>
        public static string RewardAlreadyExist {
            get {
                return ResourceManager.GetString("RewardAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Already Exist.
        /// </summary>
        public static string TrainingAlreadyExist {
            get {
                return ResourceManager.GetString("TrainingAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Anaysis Already Exist.
        /// </summary>
        public static string TrainingAnalysisAlreadyExist {
            get {
                return ResourceManager.GetString("TrainingAnalysisAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Already Exist In Calendar.
        /// </summary>
        public static string TrainingCalendarAlreadyExist {
            get {
                return ResourceManager.GetString("TrainingCalendarAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Exit Already Exist.
        /// </summary>
        public static string TypeOfExitAlreadyExisted {
            get {
                return ResourceManager.GetString("TypeOfExitAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Updated.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already used for registration, please specify another username..
        /// </summary>
        public static string UserAlreadyExistText {
            get {
                return ResourceManager.GetString("UserAlreadyExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Already Exist.
        /// </summary>
        public static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a username..
        /// </summary>
        public static string UserNameValidationError {
            get {
                return ResourceManager.GetString("UserNameValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserNameWatermarkMessage {
            get {
                return ResourceManager.GetString("UserNameWatermarkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancy already exist .
        /// </summary>
        public static string VacancyAlreadyExistText {
            get {
                return ResourceManager.GetString("VacancyAlreadyExistText", resourceCulture);
            }
        }
    }
}
